#ifndef __STDC_WANT_DEC_FP__
# define __STDC_WANT_DEC_FP__
#endif

#include <stdio.h>
#include <math.h>
#include <float.h>
#include <dpd-private.h>

#define _WANT_VC 1
#include "scaffold.c"
#ifndef DEC_INFINITY
# define DEC_INFINITY __builtin_infd32()
#endif
#ifndef DEC_NAN
# define DEC_NAN      __builtin_nand32("")
#endif
#define   plus_infty     DEC_INFINITY
#define   minus_infty    -DEC_INFINITY
#define   qnan_value     DEC_NAN
#define   snan_value     DEC_NAN

typedef struct {
  union ieee754r_Decimal32 arg0;
  union ieee754r_Decimal32 arg1;
  bool e;
} operations_t;

static const operations_t operations[] = {
  { { .sd = 0 }, { .sd = 0 },  1 },
  { { .sd = 0 }, { .sd = 1 },  1 },
  { { .sd = 1 }, { .sd = 0 },  1 },
  { { .sd = 1 }, { .sd = 1 },  1 },
  { { .sd = 10 }, { .sd = 1E+1DF },  0 },
  { { .sd = 10E+1DF }, { .sd = 10E+1DF },  1 },
  { { .sd = 100 }, { .sd = 10E+1DF },  0 },
  { { .sd = 100 }, { .sd = 1E+2DF },  0 },
  { { .sd = 0.1DF }, { .sd = 1E-2DF },  0 },
  { { .sd = 0.1DF }, { .sd = 1E-1DF },  1 },
  { { .sd = 0.1DF }, { .sd = 1E-0DF },  0 },
  { { .sd = 999 }, { .sd = 999 },  1 },
  { { .sd = 999E-1DF }, { .sd = 99.9DF },  1 },
  { { .sd = 111E-1DF }, { .sd = 22.2DF },  1 },
  { { .sd = 111E-1DF }, { .sd = 1234.2DF },  1 },
  { { .sd = 0.0DF }, { .sd = 1.1DF },  1 },
  { { .sd = 0.0DF }, { .sd = 1.11DF },  0 },
  { { .sd = 0.0DF }, { .sd = 0 },  0 },
  { { .sd = 0.0DF }, { .sd = 0.0DF },  1 },
  { { .sd = 0.0DF }, { .sd = 0.00DF },  0 },
  { { .sd = 0E+1DF }, { .sd = 0E+0DF },  0 },
  { { .sd = 0E+1DF }, { .sd = 0E+1DF },  1 },
  { { .sd = 0E+1DF }, { .sd = 0E+2DF },  0 },
  { { .sd = 0E-17DF }, { .sd = 0E-16DF },  0 },
  { { .sd = 0E-17DF }, { .sd = 0E-17DF },  1 },
  { { .sd = 0E-17DF }, { .sd = 0E-18DF },  0 },
  { { .sd = 0E-17DF }, { .sd = 0.0E-15DF },  0 },
  { { .sd = 0E-17DF }, { .sd = 0.0E-16DF },  1 },
  { { .sd = 0E-17DF }, { .sd = 0.0E-17DF },  0 },
  { { .sd = -0E-17DF }, { .sd = 0.0E-16DF },  1 },
  { { .sd = 0E-17DF }, { .sd = -0.0E-17DF },  0 },
  { { .sd = 0E-17DF }, { .sd = -0.0E-16DF },  1 },
  { { .sd = -0E-17DF }, { .sd = 0.0E-17DF },  0 },
  { { .sd = -0E-17DF }, { .sd = -0.0E-16DF },  1 },
  { { .sd = -0E-17DF }, { .sd = -0.0E-17DF },  0 },
  { { .sd = DEC32_MAX }, { .sd = DEC32_MAX },  1 },
  { { .sd = 1E-94DF }, { .sd = 1E-94DF },  1 },
  { { .sd = 1.00000000E-94DF }, { .sd = 1.00000000E-94DF },  1 },
  { { .sd = DEC32_SUBNORMAL_MIN }, { .sd = DEC32_SUBNORMAL_MIN },  1 },
  { { .sd = DEC32_MAX }, { .sd = DEC32_MAX },  1 },
  { { .sd = 1E-94DF }, { .sd = 1E-94DF },  1 },
  { { .sd = 1.00000000E-94DF }, { .sd = 1.00000000E-94DF },  1 },
  { { .sd = DEC32_SUBNORMAL_MIN }, { .sd = DEC32_SUBNORMAL_MIN },  1 },
  { { .sd = -DEC32_SUBNORMAL_MIN }, { .sd = -DEC32_SUBNORMAL_MIN },  1 },
  { { .sd = -1.00000000E-94DF }, { .sd = -1.00000000E-94DF },  1 },
  { { .sd = -1E-94DF }, { .sd = -1E-94DF },  1 },
  { { .sd = -DEC32_MAX }, { .sd = -DEC32_MAX },  1 },
  { { .sd = -DEC32_SUBNORMAL_MIN }, { .sd = -DEC32_SUBNORMAL_MIN },  1 },
  { { .sd = -1.00000000E-94DF }, { .sd = 1.00000000E-94DF },  1 },
  { { .sd = -1E-94DF }, { .sd = -1E-94DF },  1 },
  { { .sd = -DEC32_MAX }, { .sd = -DEC32_MAX },  1 },
  { { .sd = -4.00000000E-94DF }, { .sd = -1.00004000E-94DF },  1 },
  { { .sd = -4E-94DF }, { .sd = -1E-94DF },  1 },
  { { .sd = -4.00000000E-94DF }, { .sd = -1.00400000E-94DF },  1 },
  { { .sd = -4E-94DF }, { .sd = -1E-94DF },  1 },
  { { .sd = minus_infty }, { .sd = minus_infty },  1 },
  { { .sd = minus_infty }, { .sd = plus_infty },  1 },
  { { .sd = minus_infty }, { .sd = qnan_value },  0 },
  { { .sd = minus_infty }, { .sd = -7E+3DF },  0 },
  { { .sd = minus_infty }, { .sd = -7 },  0 },
  { { .sd = minus_infty }, { .sd = -7E-3DF },  0 },
  { { .sd = minus_infty }, { .sd = -0E-3DF },  0 },
  { { .sd = minus_infty }, { .sd = -0 },  0 },
  { { .sd = minus_infty }, { .sd = -0E+3DF },  0 },
  { { .sd = minus_infty }, { .sd = 0E-3DF },  0 },
  { { .sd = minus_infty }, { .sd = 0 },  0 },
  { { .sd = minus_infty }, { .sd = 0E+3DF },  0 },
  { { .sd = minus_infty }, { .sd = 7E-3DF },  0 },
  { { .sd = minus_infty }, { .sd = 7 },  0 },
  { { .sd = minus_infty }, { .sd = 7E+3DF },  0 },
  { { .sd = minus_infty }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = plus_infty }, { .sd = minus_infty },  1 },
  { { .sd = plus_infty }, { .sd = plus_infty },  1 },
  { { .sd = plus_infty }, { .sd = qnan_value },  0 },
  { { .sd = plus_infty }, { .sd = -7E+3DF },  0 },
  { { .sd = plus_infty }, { .sd = -7 },  0 },
  { { .sd = plus_infty }, { .sd = -7E-3DF },  0 },
  { { .sd = plus_infty }, { .sd = -0E-3DF },  0 },
  { { .sd = plus_infty }, { .sd = -0 },  0 },
  { { .sd = plus_infty }, { .sd = -0E+3DF },  0 },
  { { .sd = plus_infty }, { .sd = 0E-3DF },  0 },
  { { .sd = plus_infty }, { .sd = 0 },  0 },
  { { .sd = plus_infty }, { .sd = 0E+3DF },  0 },
  { { .sd = plus_infty }, { .sd = 7E-3DF },  0 },
  { { .sd = plus_infty }, { .sd = 7 },  0 },
  { { .sd = plus_infty }, { .sd = 7E+3DF },  0 },
  { { .sd = plus_infty }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = qnan_value }, { .sd = minus_infty },  0 },
  { { .sd = qnan_value }, { .sd = plus_infty },  0 },
  { { .sd = qnan_value }, { .sd = qnan_value },  1 },
  { { .sd = qnan_value }, { .sd = -7E+3DF },  0 },
  { { .sd = qnan_value }, { .sd = -7 },  0 },
  { { .sd = qnan_value }, { .sd = -7E-3DF },  0 },
  { { .sd = qnan_value }, { .sd = -0E-3DF },  0 },
  { { .sd = qnan_value }, { .sd = -0 },  0 },
  { { .sd = qnan_value }, { .sd = -0E+3DF },  0 },
  { { .sd = qnan_value }, { .sd = 0E-3DF },  0 },
  { { .sd = qnan_value }, { .sd = 0 },  0 },
  { { .sd = qnan_value }, { .sd = 0E+3DF },  0 },
  { { .sd = qnan_value }, { .sd = 7E-3DF },  0 },
  { { .sd = qnan_value }, { .sd = 7 },  0 },
  { { .sd = qnan_value }, { .sd = 7E+3DF },  0 },
  { { .sd = qnan_value }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  1 },
  { { .sd = -7E+3DF }, { .sd = minus_infty },  0 },
  { { .sd = -7E+3DF }, { .sd = plus_infty },  0 },
  { { .sd = -7E+3DF }, { .sd = qnan_value },  0 },
  { { .sd = -7E+3DF }, { .sd = -7E+3DF },  1 },
  { { .sd = -7E+3DF }, { .sd = -7 },  0 },
  { { .sd = -7E+3DF }, { .sd = -7E-3DF },  0 },
  { { .sd = -7E+3DF }, { .sd = -0E-3DF },  0 },
  { { .sd = -7E+3DF }, { .sd = -0 },  0 },
  { { .sd = -7E+3DF }, { .sd = -0E+3DF },  1 },
  { { .sd = -7E+3DF }, { .sd = 0E-3DF },  0 },
  { { .sd = -7E+3DF }, { .sd = 0 },  0 },
  { { .sd = -7E+3DF }, { .sd = 0E+3DF },  1 },
  { { .sd = -7E+3DF }, { .sd = 7E-3DF },  0 },
  { { .sd = -7E+3DF }, { .sd = 7 },  0 },
  { { .sd = -7E+3DF }, { .sd = 7E+3DF },  1 },
  { { .sd = -7E+3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = -7 }, { .sd = minus_infty },  0 },
  { { .sd = -7 }, { .sd = plus_infty },  0 },
  { { .sd = -7 }, { .sd = qnan_value },  0 },
  { { .sd = -7 }, { .sd = -7E+3DF },  0 },
  { { .sd = -7 }, { .sd = -7 },  1 },
  { { .sd = -7 }, { .sd = -7E-3DF },  0 },
  { { .sd = -7 }, { .sd = -0E-3DF },  0 },
  { { .sd = -7 }, { .sd = -0 },  1 },
  { { .sd = -7 }, { .sd = -0E+3DF },  0 },
  { { .sd = -7 }, { .sd = 0E-3DF },  0 },
  { { .sd = -7 }, { .sd = 0 },  1 },
  { { .sd = -7 }, { .sd = 0E+3DF },  0 },
  { { .sd = -7 }, { .sd = 7E-3DF },  0 },
  { { .sd = -7 }, { .sd = 7 },  1 },
  { { .sd = -7 }, { .sd = 7E+3DF },  0 },
  { { .sd = -7 }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = -7E-3DF }, { .sd = minus_infty },  0 },
  { { .sd = -7E-3DF }, { .sd = plus_infty },  0 },
  { { .sd = -7E-3DF }, { .sd = qnan_value },  0 },
  { { .sd = -7E-3DF }, { .sd = -7E+3DF },  0 },
  { { .sd = -7E-3DF }, { .sd = -7 },  0 },
  { { .sd = -7E-3DF }, { .sd = -7E-3DF },  1 },
  { { .sd = -7E-3DF }, { .sd = -0E-3DF },  1 },
  { { .sd = -7E-3DF }, { .sd = -0 },  0 },
  { { .sd = -7E-3DF }, { .sd = -0E+3DF },  0 },
  { { .sd = -7E-3DF }, { .sd = 0E-3DF },  1 },
  { { .sd = -7E-3DF }, { .sd = 0 },  0 },
  { { .sd = -7E-3DF }, { .sd = 0E+3DF },  0 },
  { { .sd = -7E-3DF }, { .sd = 7E-3DF },  1 },
  { { .sd = -7E-3DF }, { .sd = 7 },  0 },
  { { .sd = -7E-3DF }, { .sd = 7E+3DF },  0 },
  { { .sd = -7E-3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = -0E-3DF }, { .sd = minus_infty },  0 },
  { { .sd = -0E-3DF }, { .sd = plus_infty },  0 },
  { { .sd = -0E-3DF }, { .sd = qnan_value },  0 },
  { { .sd = -0E-3DF }, { .sd = -7E+3DF },  0 },
  { { .sd = -0E-3DF }, { .sd = -7 },  0 },
  { { .sd = -0E-3DF }, { .sd = -7E-3DF },  1 },
  { { .sd = -0E-3DF }, { .sd = -0E-3DF },  1 },
  { { .sd = -0E-3DF }, { .sd = -0 },  0 },
  { { .sd = -0E-3DF }, { .sd = -0E+3DF },  0 },
  { { .sd = -0E-3DF }, { .sd = 0E-3DF },  1 },
  { { .sd = -0E-3DF }, { .sd = 0 },  0 },
  { { .sd = -0E-3DF }, { .sd = 0E+3DF },  0 },
  { { .sd = -0E-3DF }, { .sd = 7E-3DF },  1 },
  { { .sd = -0E-3DF }, { .sd = 7 },  0 },
  { { .sd = -0E-3DF }, { .sd = 7E+3DF },  0 },
  { { .sd = -0E-3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = -0 }, { .sd = minus_infty },  0 },
  { { .sd = -0 }, { .sd = plus_infty },  0 },
  { { .sd = -0 }, { .sd = qnan_value },  0 },
  { { .sd = -0 }, { .sd = -7E+3DF },  0 },
  { { .sd = -0 }, { .sd = -7 },  1 },
  { { .sd = -0 }, { .sd = -7E-3DF },  0 },
  { { .sd = -0 }, { .sd = -0E-3DF },  0 },
  { { .sd = -0 }, { .sd = -0 },  1 },
  { { .sd = -0 }, { .sd = -0E+3DF },  0 },
  { { .sd = -0 }, { .sd = 0E-3DF },  0 },
  { { .sd = -0 }, { .sd = 0 },  1 },
  { { .sd = -0 }, { .sd = 0E+3DF },  0 },
  { { .sd = -0 }, { .sd = 7E-3DF },  0 },
  { { .sd = -0 }, { .sd = 7 },  1 },
  { { .sd = -0 }, { .sd = 7E+3DF },  0 },
  { { .sd = -0 }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = -0E+3DF }, { .sd = minus_infty },  0 },
  { { .sd = -0E+3DF }, { .sd = plus_infty },  0 },
  { { .sd = -0E+3DF }, { .sd = qnan_value },  0 },
  { { .sd = -0E+3DF }, { .sd = -7E+3DF },  1 },
  { { .sd = -0E+3DF }, { .sd = -7 },  0 },
  { { .sd = -0E+3DF }, { .sd = -7E-3DF },  0 },
  { { .sd = -0E+3DF }, { .sd = -0E-3DF },  0 },
  { { .sd = -0E+3DF }, { .sd = -0 },  0 },
  { { .sd = -0E+3DF }, { .sd = -0E+3DF },  1 },
  { { .sd = -0E+3DF }, { .sd = 0E-3DF },  0 },
  { { .sd = -0E+3DF }, { .sd = 0 },  0 },
  { { .sd = -0E+3DF }, { .sd = 0E+3DF },  1 },
  { { .sd = -0E+3DF }, { .sd = 7E-3DF },  0 },
  { { .sd = -0E+3DF }, { .sd = 7 },  0 },
  { { .sd = -0E+3DF }, { .sd = 7E+3DF },  1 },
  { { .sd = -0E+3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 0E-3DF }, { .sd = minus_infty },  0 },
  { { .sd = 0E-3DF }, { .sd = plus_infty },  0 },
  { { .sd = 0E-3DF }, { .sd = qnan_value },  0 },
  { { .sd = 0E-3DF }, { .sd = -7E+3DF },  0 },
  { { .sd = 0E-3DF }, { .sd = -7 },  0 },
  { { .sd = 0E-3DF }, { .sd = -7E-3DF },  1 },
  { { .sd = 0E-3DF }, { .sd = -0E-3DF },  1 },
  { { .sd = 0E-3DF }, { .sd = -0 },  0 },
  { { .sd = 0E-3DF }, { .sd = -0E+3DF },  0 },
  { { .sd = 0E-3DF }, { .sd = 0E-3DF },  1 },
  { { .sd = 0E-3DF }, { .sd = 0 },  0 },
  { { .sd = 0E-3DF }, { .sd = 0E+3DF },  0 },
  { { .sd = 0E-3DF }, { .sd = 7E-3DF },  1 },
  { { .sd = 0E-3DF }, { .sd = 7 },  0 },
  { { .sd = 0E-3DF }, { .sd = 7E+3DF },  0 },
  { { .sd = 0E-3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 0 }, { .sd = minus_infty },  0 },
  { { .sd = 0 }, { .sd = plus_infty },  0 },
  { { .sd = 0 }, { .sd = qnan_value },  0 },
  { { .sd = 0 }, { .sd = -7E+3DF },  0 },
  { { .sd = 0 }, { .sd = -7 },  1 },
  { { .sd = 0 }, { .sd = -7E-3DF },  0 },
  { { .sd = 0 }, { .sd = -0E-3DF },  0 },
  { { .sd = 0 }, { .sd = -0 },  1 },
  { { .sd = 0 }, { .sd = -0E+3DF },  0 },
  { { .sd = 0 }, { .sd = 0E-3DF },  0 },
  { { .sd = 0 }, { .sd = 0 },  1 },
  { { .sd = 0 }, { .sd = 0E+3DF },  0 },
  { { .sd = 0 }, { .sd = 7E-3DF },  0 },
  { { .sd = 0 }, { .sd = 7 },  1 },
  { { .sd = 0 }, { .sd = 7E+3DF },  0 },
  { { .sd = 0 }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 0E+3DF }, { .sd = minus_infty },  0 },
  { { .sd = 0E+3DF }, { .sd = plus_infty },  0 },
  { { .sd = 0E+3DF }, { .sd = qnan_value },  0 },
  { { .sd = 0E+3DF }, { .sd = -7E+3DF },  1 },
  { { .sd = 0E+3DF }, { .sd = -7 },  0 },
  { { .sd = 0E+3DF }, { .sd = -7E-3DF },  0 },
  { { .sd = 0E+3DF }, { .sd = -0E-3DF },  0 },
  { { .sd = 0E+3DF }, { .sd = -0 },  0 },
  { { .sd = 0E+3DF }, { .sd = -0E+3DF },  1 },
  { { .sd = 0E+3DF }, { .sd = 0E-3DF },  0 },
  { { .sd = 0E+3DF }, { .sd = 0 },  0 },
  { { .sd = 0E+3DF }, { .sd = 0E+3DF },  1 },
  { { .sd = 0E+3DF }, { .sd = 7E-3DF },  0 },
  { { .sd = 0E+3DF }, { .sd = 7 },  0 },
  { { .sd = 0E+3DF }, { .sd = 7E+3DF },  1 },
  { { .sd = 0E+3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 7E-3DF }, { .sd = minus_infty },  0 },
  { { .sd = 7E-3DF }, { .sd = plus_infty },  0 },
  { { .sd = 7E-3DF }, { .sd = qnan_value },  0 },
  { { .sd = 7E-3DF }, { .sd = -7E+3DF },  0 },
  { { .sd = 7E-3DF }, { .sd = -7 },  0 },
  { { .sd = 7E-3DF }, { .sd = -7E-3DF },  1 },
  { { .sd = 7E-3DF }, { .sd = -0E-3DF },  1 },
  { { .sd = 7E-3DF }, { .sd = -0 },  0 },
  { { .sd = 7E-3DF }, { .sd = -0E+3DF },  0 },
  { { .sd = 7E-3DF }, { .sd = 0E-3DF },  1 },
  { { .sd = 7E-3DF }, { .sd = 0 },  0 },
  { { .sd = 7E-3DF }, { .sd = 0E+3DF },  0 },
  { { .sd = 7E-3DF }, { .sd = 7E-3DF },  1 },
  { { .sd = 7E-3DF }, { .sd = 7 },  0 },
  { { .sd = 7E-3DF }, { .sd = 7E+3DF },  0 },
  { { .sd = 7E-3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 7 }, { .sd = minus_infty },  0 },
  { { .sd = 7 }, { .sd = plus_infty },  0 },
  { { .sd = 7 }, { .sd = qnan_value },  0 },
  { { .sd = 7 }, { .sd = -7E+3DF },  0 },
  { { .sd = 7 }, { .sd = -7 },  1 },
  { { .sd = 7 }, { .sd = -7E-3DF },  0 },
  { { .sd = 7 }, { .sd = -0E-3DF },  0 },
  { { .sd = 7 }, { .sd = -0 },  1 },
  { { .sd = 7 }, { .sd = -0E+3DF },  0 },
  { { .sd = 7 }, { .sd = 0E-3DF },  0 },
  { { .sd = 7 }, { .sd = 0 },  1 },
  { { .sd = 7 }, { .sd = 0E+3DF },  0 },
  { { .sd = 7 }, { .sd = 7E-3DF },  0 },
  { { .sd = 7 }, { .sd = 7 },  1 },
  { { .sd = 7 }, { .sd = 7E+3DF },  0 },
  { { .sd = 7 }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 7E+3DF }, { .sd = minus_infty },  0 },
  { { .sd = 7E+3DF }, { .sd = plus_infty },  0 },
  { { .sd = 7E+3DF }, { .sd = qnan_value },  0 },
  { { .sd = 7E+3DF }, { .sd = -7E+3DF },  1 },
  { { .sd = 7E+3DF }, { .sd = -7 },  0 },
  { { .sd = 7E+3DF }, { .sd = -7E-3DF },  0 },
  { { .sd = 7E+3DF }, { .sd = -0E-3DF },  0 },
  { { .sd = 7E+3DF }, { .sd = -0 },  0 },
  { { .sd = 7E+3DF }, { .sd = -0E+3DF },  1 },
  { { .sd = 7E+3DF }, { .sd = 0E-3DF },  0 },
  { { .sd = 7E+3DF }, { .sd = 0 },  0 },
  { { .sd = 7E+3DF }, { .sd = 0E+3DF },  1 },
  { { .sd = 7E+3DF }, { .sd = 7E-3DF },  0 },
  { { .sd = 7E+3DF }, { .sd = 7 },  0 },
  { { .sd = 7E+3DF }, { .sd = 7E+3DF },  1 },
  { { .sd = 7E+3DF }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = minus_infty },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = plus_infty },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = qnan_value },  1 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -7E+3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -7 },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -7E-3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -0E-3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -0 },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = -0E+3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 0E-3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 0 },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 0E+3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 7E-3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 7 },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 7E+3DF },  0 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  1 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  1 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  1 },
  { { .sd = qnan_value }, { .sd = qnan_value },  1 },
  { { .sd = qnan_value }, { .sd = qnan_value },  1 },
  { { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} }, { .sd = 3 },  0 },
  { { .sd = qnan_value }, { .sd = 3 },  0 },
  { { .sd = 4 }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = 3 }, { .sd = qnan_value },  0 },
  { { .sd = plus_infty }, { .ieee_nan = {.c = 0x1f,.signaling_nan = 1} },  0 },
  { { .sd = minus_infty }, { .sd = qnan_value },  0 },
};
static const int operations_size =     sizeof(operations)/sizeof(operations[0]);

int main (void) {
  int i;
  for (i = 0; i < operations_size; ++i) {
    bool ret = samequantumd32 ( operations[i].arg0.sd , operations[i].arg1.sd );
    printf ("samequantumd32 ( %.7HgDF , %.7HgDF ) = %d",  operations[i].arg0.sd , operations[i].arg1.sd , ret);
    _VC_P (__FILE__, __LINE__, operations[i].e, ret, "%d");
  }

  _REPORT ();

  return fail;
}
